spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          batch_size: 100
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:55000/postgres
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
    maximum-pool-size=: 100
logging:
  level:
    ROOT: INFO